spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: cortizq
    url: jdbc:oracle:thin:@localhost:1522/tst_latest
    password: tstpwd
  application:
    name: csoftz-mvc-oracle-country-use-starter
logging:
  level:
    com:
      example:
        countryapp: DEBUG
    org:
      springframework:
        jdbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exposes all endpoints
      base-path: /actuator  # Default base path for actuator endpoints
  endpoint:
    health:
      show-details: always